### ISSUE TITLE
Q: How to forward data to a local tcp server?

### ISSUE THREAD

**Issue by oleid** [jonhoo/async-ssh#6]
Hey there,

to access a host behind a ssh server, I  need to to SSH forwarding (or set a proxy connection in my ssh config).  Naturally, I can do the forwarding manually. But it would be nice to be able to do it automatically. Thus, I tried something like:

```rust
async fn forward_connection(sess: &mut async_ssh2::Session, w: &str, port: u16) -> Result<(), Box<dyn std::error::Error>>
{
    use futures::join;

    let listener = async_std::net::TcpListener::bind("localhost:0").await?;

    let mut incoming = listener.incoming();

    while let Some(stream) = incoming.next().await {
        let stream = stream?;
        let ssh = sess.channel_direct_tcpip(w, port, None).await?;

        let (tcp_rx, tcp_tx) = &mut (&stream, &stream);
        let (ssh_rx, ssh_tx, ) =&mut (ssh, &ssh);

        let a_to_b = async_std::io::copy(tcp_rx, ssh_tx);
        let b_to_a = async_std::io::copy(ssh_rx, tcp_tx);

        join!(a_to_b, b_to_a).await
    }
    Ok(())
}
``` 

This is a modified version of `async_std`'s TcpListener example (https://docs.rs/async-std/1.6.0-beta.1/async_std/net/struct.TcpListener.html). Yet, it doesn't work :

```
error[E0277]: the trait bound `&async_ssh2::channel::Channel: futures_io::if_std::AsyncWrite` is not satisfied
   --> src/main.rs:120:50
    |
120 |         let a_to_b = async_std::io::copy(tcp_rx, ssh_tx);
    |                                                  ^^^^^^ the trait `futures_io::if_std::AsyncWrite` is not implemented for `&async_ssh2::channel::Channel`
    | 
```

What would be the recommended way to do something like that?

**Comment by jonhoo** [comment]
Hi there!

So, there are two reasons this doesn't work. The first is that this crate is pretty outdated, and I probably use it for anything "real". You probably want to either use `thrussh` directly these days, or something like [`openssh`](https://docs.rs/openssh/). The second, and perhaps more important one, is that both `thrussh` and `openssh` are based on Tokio, not async-std. The runtimes use different underlying I/O implementations, and crucially, different `AsyncRead` and `AsyncWrite` traits, so you won't be able to use the async ssh crates on `async-std`.

**Comment by oleid** [comment]
Oh, this is embarrassing. I use the async-ssh2 crate, not this one.  I'm very sorry for the noise! :)
