### ISSUE TITLE
How to copy/transfer a directory from one Linux server to another via SCP/SFTP with lib

### ISSUE THREAD

**Issue by insinfo** [jonhoo/async-ssh#7]
I would like to know how to copy a directory from my linux server to my local Windows machine, I currently do this through libssh using dart, but I am interested in doing this in rust in order to reduce memory and CPU usage and improve speed.

**Comment by jonhoo** [comment]
This library was and is very much a work-in-progress that is arguably surpassed by others at this point. I would recommend looking at something like [`openssh`](https://docs.rs/openssh/) instead :)
